export const CREATE_ASSESSMENT_SUCCESS = "CREATE_ASSESSMENT_SUCCESS";
export const UPDATE_ASSESSMENT_SUCCESS = "UPDATE_ASSESSMENT_SUCCESS";
export const DELETE_ASSESSMENT_SUCCESS = "DELETE_ASSESSMENT_SUCCESS";
export const LOAD_ASSESSMENT_SUCCESS = "LOAD_ASSESSMENT_SUCCESS";
export const FILTER_ASSESSMENT_SUCCESS = "FILTER_ASSESSMENT_SUCCESS";
