export const CREATE_ASSESSMENT_SUCCESS = "CREATE_ASSESSMENT_SUCCESS";
export const UPDATE_ASSESSMENT_SUCCESS = "UPDATE_ASSESSMENT_SUCCESS";
export const DELETE_ASSESSMENT_SUCCESS = "DELETE_ASSESSMENT_SUCCESS";
export const LOAD_ASSESSMENT_SUCCESS = "LOAD_ASSESSMENT_SUCCESS";

export const CREATE_QUESTION_SUCCESS = "CREATE_QUESTION_SUCCESS";
export const UPDATE_QUESTION_SUCCESS = "UPDATE_QUESTION_SUCCESS";
export const DELETE_QUESTION_SUCCESS = "DELETE_QUESTION_SUCCESS";
export const LOAD_QUESTION_SUCCESS = "LOAD_QUESTION_SUCCESS";

export const LOAD_PREDEFINED_DATA_SUCCESS = "LOAD_PREDEFINED_DATA_SUCCESS";
